const DatagridActionsTypes = {
    SET_NB_ROWS_PER_PAGE: 'SET_NB_ROWS_PER_PAGE',
    TOGGLE_IS_FILTERABLE: 'TOGGLE_IS_FILTERABLE',
    TOGGLE_IS_SEARCHABLE: 'TOGGLE_IS_SEARCHABLE',
    TOGGLE_IS_EXPORTABLE: 'TOGGLE_IS_EXPORTABLE',
    TOGGLE_IS_GROUPABLE: 'TOGGLE_IS_GROUPABLE',
    TOGGLE_IS_DRAGGABLE: 'TOGGLE_IS_DRAGGABLE',
    TOGGLE_IS_SELECTABLE: 'TOGGLE_IS_SELECTABLE',
    ADD_TO_DATAGRID_STORAGE: 'ADD_TO_DATAGRID_STORAGE',
    SHOW_COLUMN_CHOOSER: 'SHOW_COLUMN_CHOOSER',
    ADD_DATAGRID_ROW: 'ADD_DATAGRID_ROW',
    EDIT_DATAGRID_ROW: 'EDIT_DATAGRID_ROW',
    DELETE_DATAGRID_ROW: 'DELETE_DATAGRID_ROW',
    DELETE_MULTIPLE_DATAGRID_ROW: 'DELETE_MULTIPLE_DATAGRID_ROW',
};

export default DatagridActionsTypes;