const LayoutActionsTypes = {
    FETCH_LAYOUT_START: 'FETCH_LAYOUT_START',
    FETCH_LAYOUT_SUCCESS: 'FETCH_LAYOUT_SUCCESS',
    FETCH_LAYOUT_FAILURE: 'FETCH_LAYOUT_FAILURE',
    ADD_LAYOUT_ITEM: 'ADD_LAYOUT_ITEM',
    EDIT_LAYOUT_ITEM: 'EDIT_LAYOUT_ITEM',
    DELETE_LAYOUT_ITEM: 'DELETE_LAYOUT_ITEM',
    SET_THEME: 'SET_THEME',
    TOGGLE_DRAWER: 'TOGGLE_DRAWER',
    TOGGLE_DRAWER_ON_FOCUS: 'TOGGLE_DRAWER_ON_FOCUS',
    TOGGLE_DARK_THEME: 'TOGGLE_DARK_THEME',
    TOGGLE_ITEMS_ON_FOCUS: 'TOGGLE_ITEMS_ON_FOCUS',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
    REMOVE_ERROR: 'REMOVE_ERROR'
};

export default LayoutActionsTypes;